# Generated by Django 3.2.7 on 2021-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='user',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='nin',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
