# Generated by Django 3.2.7 on 2021-11-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211120_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nin',
        ),
    ]
